module.exports = {
  sections: [
    {
      title: "Brand Bar",
      description: "Highlight a few key partners or brands",
      sectionName: "boodl-brandbar",
      planLevel: 2,
      tags: ["Brands & Icons"],
      version: 1,
    },
    {
      title: "Client Bar",
      description: "Feature some of your top clients",
      sectionName: "boodl-clientbar",
      planLevel: 2,
      tags: ["Brands & Icons"],
      version: 1,
    },
    {
      title: "Collection Banner",
      description: "Display your collections using a slideshow style",
      sectionName: "boodl-collectionbanner",
      planLevel: 2,
      tags: ["Collections"],
      version: 1,
    },
    {
      title: "Contact Form",
      description: "Make it easy for customers to reach you",
      sectionName: "boodl-contactform",
      planLevel: 2,
      tags: ["Contact"],
      version: 1,
    },
    {
      title: "Contact Map",
      description: "Show customers where they can find you",
      sectionName: "boodl-contactmap",
      planLevel: 2,
      tags: ["Contact"],
      version: 1,
    },
    {
      title: "FAQ",
      description: "Answer customers' most common questions",
      sectionName: "boodl-faq",
      planLevel: 1,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Header with Subtitle",
      description: "Capture attention with this subtle and modern header",
      sectionName: "boodl-header1",
      planLevel: 2,
      tags: ["Landing Pages"],
      version: 1,
    },
    {
      title: "Hero Video",
      description: "Captivate users with a bold title and background video",
      sectionName: "boodl-herovideo",
      planLevel: 2,
      tags: ["Landing Pages"],
      version: 1,
    },
    {
      title: "Hottest Sellers",
      description: "Showcase your best selling products",
      sectionName: "boodl-hottestsellers",
      planLevel: 1,
      tags: ["Products"],
      version: 1,
    },
    {
      title: "Icon Bar",
      description: "Display brand values with relevant icons",
      sectionName: "boodl-iconbar",
      planLevel: 1,
      tags: ["Brands & Icons"],
      version: 1,
    },
    {
      title: "Image and Text",
      description: "Show and tell with this side by side image and text",
      sectionName: "boodl-imgandtext",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Instagram Gallery",
      description: "Flaunt your feed",
      sectionName: "boodl-IGgallery",
      planLevel: 2,
      tags: ["Image Galleries"],
      version: 1,
    },
    {
      title: "Instagram Post",
      description: "Showcase your favourite posts",
      sectionName: "boodl-instapost",
      planLevel: 2,
      tags: ["Social & Reach"],
      version: 1,
    },
    {
      title: "Link Cards",
      description: "Create visually elegant links",
      sectionName: "boodl-linkcards",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Masonry",
      description: "Display your photos using a masonry grid",
      sectionName: "boodl-masonry",
      planLevel: 2,
      tags: ["Image Galleries"],
      version: 1,
    },
    {
      title: "Modern Hero Layout",
      description:
        "Grab customer attention with this modern and stylish banner",
      sectionName: "boodl-hero1",
      planLevel: 2,
      tags: ["Landing Pages"],
      version: 1,
    },
    {
      title: "Newsletter Subscription",
      description: "Get customers to subscribe to your newsletter",
      sectionName: "boodl-newslettersub",
      planLevel: 2,
      tags: ["Social & Reach"],
      version: 1,
    },
    {
      title: "Page Content",
      description: "Display page content in a simple way",
      sectionName: "boodl-pagecontent",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Parallax Text",
      description:
        "Display text that moves sideways as you scroll down the page",
      sectionName: "boodl-parallaxtext",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Percent Bars",
      description: "Demonstrate your strengths in a visual way",
      sectionName: "boodl-percentbars",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Popular Products",
      description: "Promote your best products",
      sectionName: "boodl-popularproducts",
      planLevel: 2,
      tags: ["Products"],
      version: 1,
    },
    {
      title: "Primary Header",
      description: "Be bold with this big header",
      sectionName: "boodl-ctaheader2",
      planLevel: 1,
      tags: ["Title Headers"],
      version: 1,
    },
    {
      title: "Profile",
      description: "Connect with your customers with a personal message",
      sectionName: "boodl-profile",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Simple Text",
      description: "Present some text without any distractions",
      sectionName: "boodl-simpletext",
      planLevel: 1,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Simple Text Header",
      description: "Organize your site with this classic header",
      sectionName: "boodl-simpletextheader",
      planLevel: 1,
      tags: ["Title Headers"],
      version: 1,
    },
    {
      title: "Slideshow",
      description: "Present information visually with this slideshow",
      sectionName: "boodl-slideshow",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Social Icons",
      description: "Connect customers to all your social media accounts",
      sectionName: "boodl-socialicons",
      planLevel: 2,
      tags: ["Social & Reach"],
      version: 1,
    },
    {
      title: "Stat Bar",
      description: "Showcase your statistics",
      sectionName: "boodl-statbar",
      planLevel: 1,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Subheader with Icon",
      description: "Keep users engaged with this subheader",
      sectionName: "boodl-ctaheader",
      planLevel: 2,
      tags: ["Title Headers"],
      version: 1,
    },
    {
      title: "Testimonials",
      description: "Highlight customer testimonials",
      sectionName: "boodl-testimonials",
      planLevel: 1,
      tags: ["Testimonials"],
      version: 1,
    },
    {
      title: "Text 3 Image",
      description: "Feature three images along with some text",
      sectionName: "boodl-text3img",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Text Image Background",
      description: "Say something important with this section",
      sectionName: "boodl-textimgbg",
      planLevel: 2,
      tags: ["Title Headers"],
      version: 1,
    },
    {
      title: "Three Pillars",
      description: "Like one pillar, three times",
      sectionName: "boodl-threepillars",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Text and Video",
      description:
        "Showcase your product with a side by side value prop and video",
      sectionName: "boodl-textwithvideo",
      planLevel: 2,
      tags: ["Content"],
      version: 1,
    },
    {
      title: "Social Media Reviews",
      description: "Highlight your favorite customer social media reviews",
      sectionName: "boodl-socialreviews",
      planLevel: 2,
      tags: ["Testimonials"],
      version: 1,
    },
  ],
};
